version: '3'

services:
  fd_serving:
    image: registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10
    container_name: fd_serving
    restart: unless-stopped
    volumes:
      # 
      - /data/Git_Repository/Sports_AI/sportai.py/:/workspaces:rw
      # 测试用的数据，如示例视频
      - /data/Git_Repository/Sports_AI/AI/dataset/:/workspaces/data/:ro
      # Linux下回显需要
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - CUDA_MODULE_LOADING=${CUDA_MODULE_LOADING:-LAZY}
      - DISPLAY=${DISPLAY:-192.168.1.10:0.0}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              # driver: nvidia
              # count: all
    privileged: true
    # Linux下回显需要
    network_mode: "host"
    # ports:
    #   - "8080:8080"
    stdin_open: true
    tty: true
    command: /bin/bash
